# ----------- CONFIGURABLE START -----------
title:            "Procedural Generation Ruleset"
description:      "An Easy Terrain Config Parser and Processor"
url:              https://gammagames.github.io/procedural-generation-ruleset/

links:
  - name:         Home
    url:          /
  - name:         Download
    url:          /download
  - name:         GitHub
    url:          https://github.com/gammagames/procedural-generation-ruleset/
    external:     true

# latest_tag: "1.0"
# fetch_releases: false

# ------------ CONFIGURABLE END ------------

defaults:
  - values:
      layout: "default"
      fetch_releases: false
