# ----------- CONFIGURABLE START -----------
title:            "Mushy Terrain Generator"
description:      "A Terrain Config Parser and Processor"
url:              https://gammagames.github.io/mushy-terrain/

links:
  - name:         Home
    url:          /
  - name:         Download
    url:          /download
  - name:         GitHub
    url:          https://github.com/GammaGames/mushy-terrain
    external:     true

# ------------ CONFIGURABLE END ------------

defaults:
  - values:
      layout: "default"
